"""add_sales_and_unit_conversion

Revision ID: 5bb161bcd39a
Revises: decacbaae560
Create Date: 2026-08-23 00:44:01.331852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb161bcd39a'
down_revision: Union[str, Sequence[str], None] = 'decacbaae560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.add_column('product_variants', sa.Column('secondary_unit_id', sa.Integer(), nullable=True))
    op.add_column('product_variants', sa.Column('conversion_factor', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'product_variants', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'product_variants', 'units', ['secondary_unit_id'], ['id'])
    op.add_column('products', sa.Column('secondary_unit_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('conversion_factor', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'products', 'units', ['secondary_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'conversion_factor')
    op.drop_column('products', 'secondary_unit_id')
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_column('product_variants', 'conversion_factor')
    op.drop_column('product_variants', 'secondary_unit_id')
    op.drop_column('product_variants', 'unit_id')
    # ### end Alembic commands ###
